version: 2.1

executors:
  go:
    parameters:
      goversion:
        type: string
        default: "11"
    working_directory: /go/src/github.com/honeycombio/beeline-go
    docker:
      - image: circleci/golang:1.<< parameters.goversion >>

jobs:
  test_beeline:
    parameters:
      goversion:
        type: string
        default: "11"
    executor:
      name: go
      goversion: "<< parameters.goversion >>"
    steps:
      - checkout
      - run:
          name: go-test
          command: go test -mod=readonly -race -v ./...
          environment:
            GO111MODULE: on

workflows:
  build:
    jobs:
      - test_beeline:
          goversion: "11"
      - test_beeline:
          goversion: "12"
      - test_beeline:
          goversion: "13"
      - test_beeline:
          goversion: "14"
